# Pre-commit hooks configuration
# See https://pre-commit.com for more information

default_language_version:
  python: python3.13

repos:
  # Ruff - Fast Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix]
        name: ruff lint
      - id: ruff-format
        name: ruff format

  # Security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: \.lock$|\.example$

  # YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-d, '{extends: default, rules: {line-length: {max: 120}}}']

  # Trailing whitespace and file endings
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: mixed-line-ending
      # Trunk-based development: We commit directly to main
      # Enable this if you want to enforce feature branches
      # - id: no-commit-to-branch
      #   args: ['--branch', 'main']

  # Terraform formatting (disabled until tflint is installed)
  # - repo: https://github.com/antonbabenko/pre-commit-terraform
  #   rev: v1.96.2
  #   hooks:
  #     - id: terraform_fmt
  #     - id: terraform_validate
  #     - id: terraform_tflint

  # SQL formatting with SQLFluff
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.2.0
    hooks:
      - id: sqlfluff-lint
        files: \.(sql|dml|ddl)$
      - id: sqlfluff-fix
        files: \.(sql|dml|ddl)$

  # MyPy type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        files: ^src/
        additional_dependencies: [types-pyyaml]
        args: [
          --python-version=3.13,
          --warn-return-any,
          --warn-unused-configs,
          --disallow-untyped-defs,
          --disallow-incomplete-defs,
          --check-untyped-defs,
          --disallow-untyped-decorators,
          --no-implicit-optional,
          --warn-redundant-casts,
          --warn-unused-ignores,
          --warn-no-return,
          --warn-unreachable,
          --strict-equality,
        ]

# Configuration for specific file types
files: ^(src/|tests/|scripts/|terraform/|sql/)
exclude: |
  (?x)^(
    .*/migrations/.*|
    .*\.egg-info/.*|
    build/.*|
    dist/.*|
    .venv/.*|
    venv/.*|
    .terraform/.*
  )$