"""sync server defaults

Revision ID: 500e99a283fd
Revises: f9d7361812e9
Create Date: 2025-08-01 11:06:15.258790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_extension import PGExtension
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = '500e99a283fd'
down_revision: Union[str, Sequence[str], None] = 'f9d7361812e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='audit')
    op.alter_column('addresses', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('cart_items', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('carts', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('categories', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('customer_consents', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('customers', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('inventory', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('locations', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('order_items', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('orders', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('payment_methods', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('payments', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('product_prices', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('product_variants', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('products', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('reviews', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    public_uuid_ossp = PGExtension(
        schema="public",
        signature="uuid-ossp"
    )
    op.drop_entity(public_uuid_ossp)

    public_pgcrypto = PGExtension(
        schema="public",
        signature="pgcrypto"
    )
    op.drop_entity(public_pgcrypto)

    public_btree_gin = PGExtension(
        schema="public",
        signature="btree_gin"
    )
    op.drop_entity(public_btree_gin)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    public_btree_gin = PGExtension(
        schema="public",
        signature="btree_gin"
    )
    op.create_entity(public_btree_gin)

    public_pgcrypto = PGExtension(
        schema="public",
        signature="pgcrypto"
    )
    op.create_entity(public_pgcrypto)

    public_uuid_ossp = PGExtension(
        schema="public",
        signature="uuid-ossp"
    )
    op.create_entity(public_uuid_ossp)

    op.alter_column('reviews', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('products', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('product_variants', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('product_prices', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('payments', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('payment_methods', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('orders', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('order_items', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('locations', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('inventory', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('customers', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('customer_consents', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('categories', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('carts', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('cart_items', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('addresses', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='ecommerce')
    op.alter_column('audit_log', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('uuid_generate_v7()'),
               existing_nullable=False,
               schema='audit')
    # ### end Alembic commands ###
